version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my_network        

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
    command: sh -c "ls && while ! nc -z postgres 5432; do sleep 1; done && npm run deploy"
    depends_on:
      - postgres

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: